### ISSUE TITLE
not a valid cellphone

### ISSUE THREAD

**Issue by Tim2906** [mazdakpak/Sms_Bomber#1]
Hello is this script still working?

because if i install everything and start the script it asks me for a number, then i says its not valid and i get this error message:

![Screenshot_3](https://user-images.githubusercontent.com/69757707/104042773-2d9ec680-51db-11eb-9fcc-5f016ca47fd7.png)

everything i did is changing the country code from +98 to +49

**Comment by mazdakdev** [comment]
Hi thanks for contacting me 
actually yes this script is still working but the point is its only works for iran cellphones just +98 
sorry,
